---
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

constants:
  - &aws-role-arn "arn:aws:iam::731679461860:role/CircleCi-Personal-Projects"
  - &project-directory /tmp/zacmilano-dot-com

job-defaults: &job-defaults
  docker:
    - image: cimg/node:18.13.0
  resource_class: small
  working_directory: *project-directory

jobs:
  install-dependencies:
    <<: *job-defaults

    steps:
      - checkout
      # - run:
      #     name: Install Yarn
      #     command: |
      #       curl -o- -L https://yarnpkg.com/install.sh | bash
      #       yarn set version 1.22.19
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}
            - yarn-packages-v1
      - run:
          name: Install Dependencies
          command: |
            yarn install --immutable
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./.yarn/cache
      - save_cache:
          name: Cache whole project
          key: v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - *project-directory

  build:
    <<: *job-defaults
    resource_class: medium

    steps:
      - restore_cache:
          key: v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: |
            yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    <<: *job-defaults

    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          role-arn: *aws-role-arn
      - run:
          name: Deploy to S3 bucket via gatsby-plugin-s3
          command: |
            yarn run deploy
      - run:
          name: Invalidate CloudFront Cache
          command: >
            aws cloudfront create-invalidation
            --distribution-id E1BHQYZYZX50ED
            --paths "/*"

workflows:
  build_and_deploy:
    jobs:
      - install-dependencies
      - build:
          requires:
            - install-dependencies
      - deploy:
          context:
            - milano-personal-projects-context
          requires:
            - build
          filters:
            branches:
              only:
                - main
