---
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  install-dependencies:
    docker:
      - image: cimg/node:18.13.0
    resource_class: small
    working_directory: ~/zacmilano
    steps:
      - checkout
      - run:
          name: Install Yarn
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
            yarn set version 1.22.19
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}
            - yarn-packages-v1
      - run:
          name: Install Dependencies
          command: |
            yarn install --immutable
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./.yarn/cache
      - save_cache:
          name: Cache whole project
          key: v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/zacmilano
  build:
    docker:
      - image: cimg/node:18.13.0
    resource_class: small
    working_directory: ~/zacmilano
    steps:
      - restore_cache:
          key: v1-repo-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: |
            yarn run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: cimg/node:18.13.0
    resource_class: small
    working_directory: ~/zacmilano
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup
      - run:
          name: Assume IAM role to access AWS resources
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            cp .circleci/aws_config ~/.aws/config
      - run:
          name: Deploy
          command: |
            yarn run deploy
workflows:
  build_and_deploy:
    jobs:
      - install-dependencies
      - build:
          requires:
            - install-dependencies
      - deploy:
          context:
            - milano-personal-projects-context
          requires:
            - build
          filters:
            branches:
              only:
                - main
